# imports

In [70]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [71]:
path = r'C:\Users\Magsihim_AI\Desktop\Project_Statbotics\data\datasets\full_table2.csv'

df = pd.read_csv(path)

In [72]:
df

,actual_time,comp_level,event_key,key,match_number,post_result_time,set_number,time,videos,winning_alliance,...,teleopReef_topRow_nodeI,teleopReef_topRow_nodeJ,teleopReef_topRow_nodeK,teleopReef_topRow_nodeL,teleopReef_trough,wallAlgaeCount,team_number,scorePenaltyFree,possition,alliance
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",blue,...,True,False,False,True,0.0,0.0,frc2783,124.0,1,red
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",blue,...,True,True,True,False,0.0,0.0,frc2783,144.0,1,red
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",red,...,False,False,False,False,5.0,2.0,frc5045,129.0,1,red
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",red,...,True,True,True,True,1.0,0.0,frc538,112.0,1,red
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",blue,...,False,True,True,True,1.0,1.0,frc6107,61.0,1,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116377,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,5,1.752378e+09,[],red,...,False,False,False,False,6.0,0.0,frc9995,64.0,3,blue
116378,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,6,1.752379e+09,[],blue,...,False,False,False,False,1.0,0.0,frc9991,72.0,3,blue
116379,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,7,1.752380e+09,[],red,...,False,False,False,False,0.0,0.0,frc9994,65.0,3,blue
116380,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,8,1.752381e+09,[],red,...,False,True,True,True,14.0,0.0,frc9993,73.0,3,blue
116381,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,9,1.752381e+09,[],red,...,False,False,False,False,1.0,0.0,frc9991,57.0,3,blue

# prepares

In [73]:
#dropping teams with less than 10 games
teams_to_drop = ['frc9990', 'frc9991', 'frc9992', 'frc9993', 'frc9994', 'frc9995', 'frc9996', 'frc9997', 'frc9998', 'frc9999']

for team in df['team_number'].unique():
    if df.loc[df['team_number'] == team].shape[0] < 10:
        teams_to_drop.append(team)

df = df[~df['team_number'].isin(teams_to_drop)]

In [ ]:
#adding column "win"
df['win'] = df['winning_alliance'] == df['alliance']

C:\Users\Magsihim_AI\AppData\Local\Temp\ipykernel_13916\1230158382.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['win'] = df['winning_alliance'] == df['alliance']

In [ ]:
#mapping data
df["comp_level"] = df["comp_level"].map({'qm': 1, 'sf': 2, 'f': 3})
df['winning_alliance'] = df['winning_alliance'].map({'blue': 1, 'red': 2})
df['winning_alliance'] = df['winning_alliance'].fillna(0)
df['alliance'] = df['alliance'].map({'blue': 1, 'red': 2})
df['autoLine'] = df['autoLine'].map({'Yes': True, 'No': False})
df['endGame'] = df['endGame'].map({'Nothing': 0, 'Parked': 1, 'ShallowCage': 2, 'DeepCage':3})
df['team_number'] = df['team_number'].astype(str).str.extract(r'(\d+)').astype(int)

C:\Users\Magsihim_AI\AppData\Local\Temp\ipykernel_13916\986933399.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["comp_level"] = df["comp_level"].map({'qm': 1, 'sf': 2, 'f': 3})
C:\Users\Magsihim_AI\AppData\Local\Temp\ipykernel_13916\986933399.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['winning_alliance'] = df['winning_alliance'].map({'blue': 1, 'red': 2})
C:\Users\Magsihim_AI\AppData\Local\Temp\ipykernel_13916\986933399.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['winning_alliance'] = df['winning_alliance'].fillna(0)
C:\Users\Magsihim_AI\AppData\Local\Temp\ipykernel_13916\986933399.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['alliance'] = df['alliance'].map({'blue': 1, 'red': 2})
C:\Users\Magsihim_AI\AppData\Local\Temp\ipykernel_13916\986933399.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['autoLine'] = df['autoLine'].map({'Yes': True, 'No': False})
C:\Users\Magsihim_AI\AppData\Local\Temp\ipykernel_13916\986933399.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['endGame'] = df['endGame'].map({'Nothing': 0, 'Parked': 1, 'ShallowCage': 2, 'DeepCage':3})
C:\Users\Magsihim_AI\AppData\Local\Temp\ipykernel_13916\986933399.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['team_number'] = df['team_number'].astype(str).str.extract(r'(\d+)').astype(int)

## duplicate lines

In [110]:
df.head(3)

,actual_time,comp_level,event_key,key,match_number,post_result_time,set_number,time,videos,winning_alliance,...,teleopReef_topRow_nodeJ,teleopReef_topRow_nodeK,teleopReef_topRow_nodeL,teleopReef_trough,wallAlgaeCount,team_number,scorePenaltyFree,possition,alliance,win
0,1.742056e+09,3,2025alhu,2025alhu_f1m1,1,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",1.0,...,False,False,True,0.0,0.0,2783,124.0,1,2,False
1,1.742058e+09,3,2025alhu,2025alhu_f1m2,2,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",1.0,...,True,True,False,0.0,0.0,2783,144.0,1,2,False
2,1.741960e+09,1,2025alhu,2025alhu_qm1,1,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",2.0,...,False,False,False,5.0,2.0,5045,129.0,1,2,True

In [117]:
one_team_game

0              58197
1       1741965848.0
2                  1
3           2025alhu
4      2025alhu_qm13
           ...
118             5125
119             61.0
120                1
121                1
122             True
Length: 123, dtype: object

In [126]:
data = pd.DataFrame()
key_data = df.loc[df['key'] == '2025alhu_qm13']
for i in range(1,3):
    alliance_data = key_data.loc[key_data['alliance'] == i]
    for team in alliance_data.itertuples():
        for second_team in alliance_data.loc[alliance_data['team_number'] != team[118]].itertuples():
            one_team_game = pd.Series(team)
            second_team_game = pd.Series(second_team)
            one_team_game['endGame_second_bot'] = second_team_game.iloc[64]
            one_team_game['second_team_number'] = second_team_game.iloc[118]
            one_team_game['possition_second_bot'] = second_team_game.iloc[120]
            one_team_game['autoLine_second_bot'] = second_team_game.iloc[17]

            data = pd.concat([data,one_team_game], axis = 1 )

In [127]:
data.T

,0,1,2,3,4,5,6,7,8,9,...,117,118,119,120,121,122,endGame_second_bot,second_team_number,possition_second_bot,autoLine_second_bot
0,58197,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,5125,61.0,1,1,True,1,3966,2,True
0,58197,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,5125,61.0,1,1,True,1,3959,3,True
0,77594,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,3966,61.0,2,1,True,1,5125,1,True
0,77594,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,3966,61.0,2,1,True,1,3959,3,True
0,96991,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,3959,61.0,3,1,True,1,5125,1,True
0,96991,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,3959,61.0,3,1,True,1,3966,2,True
0,6,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,7111,38.0,1,2,False,1,2502,2,True
0,6,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,7111,38.0,1,2,False,0,3814,3,True
0,19403,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,2502,38.0,2,2,False,1,7111,1,True
0,19403,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,2502,38.0,2,2,False,0,3814,3,True
0,38800,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,3814,38.0,3,2,False,1,7111,1,True
0,38800,1741965848.0,1,2025alhu,2025alhu_qm13,13,1741966032.0,1,1741966440.0,"[{'key': 'UoCPIGg3_f4', 'type': 'youtube'}]",...,0.0,3814,38.0,3,2,False,1,2502,2,True

In [ ]:
for key in df['key'].unique():

2025alhu_f1m1
2025alhu_f1m2
2025alhu_qm1
2025alhu_qm10
2025alhu_qm11
2025alhu_qm12
2025alhu_qm13
2025alhu_qm14
2025alhu_qm15
2025alhu_qm16
2025alhu_qm17
2025alhu_qm18
2025alhu_qm19
2025alhu_qm2
2025alhu_qm20
2025alhu_qm21
2025alhu_qm22
2025alhu_qm23
2025alhu_qm24
2025alhu_qm25
2025alhu_qm26
2025alhu_qm27
2025alhu_qm28
2025alhu_qm29
2025alhu_qm3
2025alhu_qm30
2025alhu_qm31
2025alhu_qm32
2025alhu_qm33
2025alhu_qm34
2025alhu_qm35
2025alhu_qm36
2025alhu_qm37
2025alhu_qm38
2025alhu_qm39
2025alhu_qm4
2025alhu_qm40
2025alhu_qm41
2025alhu_qm42
2025alhu_qm43
2025alhu_qm44
2025alhu_qm45
2025alhu_qm46
2025alhu_qm47
2025alhu_qm48
2025alhu_qm49
2025alhu_qm5
2025alhu_qm50
2025alhu_qm51
2025alhu_qm52
2025alhu_qm53
2025alhu_qm54
2025alhu_qm55
2025alhu_qm56
2025alhu_qm57
2025alhu_qm58
2025alhu_qm59
2025alhu_qm6
2025alhu_qm60
2025alhu_qm61
2025alhu_qm62
2025alhu_qm63
2025alhu_qm64
2025alhu_qm65
2025alhu_qm66
2025alhu_qm67
2025alhu_qm68
2025alhu_qm69
2025alhu_qm7
2025alhu_qm70
2025alhu_qm71
2025alhu_qm72
2025alhu_qm73
2025alhu_qm74
2025alhu_qm75
2025alhu_qm76
2025alhu_qm77
2025alhu_qm78
2025alhu_qm79
2025alhu_qm8
2025alhu_qm80
2025alhu_qm81
2025alhu_qm9
2025alhu_sf10m1
2025alhu_sf11m1
2025alhu_sf12m1
2025alhu_sf13m1
2025alhu_sf1m1
2025alhu_sf2m1
2025alhu_sf3m1
2025alhu_sf4m1
2025alhu_sf5m1
2025alhu_sf6m1
2025alhu_sf7m1
2025alhu_sf8m1
2025alhu_sf9m1
2025arc_f1m1
2025arc_f1m2
2025arc_qm1
2025arc_qm10
2025arc_qm100
2025arc_qm101
2025arc_qm102
2025arc_qm103
2025arc_qm104
2025arc_qm105
2025arc_qm106
2025arc_qm107
2025arc_qm108
2025arc_qm109
2025arc_qm11
2025arc_qm110
2025arc_qm111
2025arc_qm112
2025arc_qm113
2025arc_qm114
2025arc_qm115
2025arc_qm116
2025arc_qm117
2025arc_qm118
2025arc_qm119
2025arc_qm12
2025arc_qm120
2025arc_qm121
2025arc_qm122
2025arc_qm123
2025arc_qm124
2025arc_qm125
2025arc_qm13
2025arc_qm14
2025arc_qm15
2025arc_qm16
2025arc_qm17
2025arc_qm18
2025arc_qm19
2025arc_qm2
2025arc_qm20
2025arc_qm21
2025arc_qm22
2025arc_qm23
2025arc_qm24
2025arc_qm25
2025arc_qm26
2025arc_qm27
2025arc_qm28
2025arc_qm29
2025arc_qm3
2025arc_qm30
2025arc_qm31
2025arc_qm32
2025arc_qm33
2025arc_qm34
2025arc_qm35
2025arc_qm36
2025arc_qm37
2025arc_qm38
2025arc_qm39
2025arc_qm4
2025arc_qm40
2025arc_qm41
2025arc_qm42
2025arc_qm43
2025arc_qm44
2025arc_qm45
2025arc_qm46
2025arc_qm47
2025arc_qm48
2025arc_qm49
2025arc_qm5
2025arc_qm50
2025arc_qm51
2025arc_qm52
2025arc_qm53
2025arc_qm54
2025arc_qm55
2025arc_qm56
2025arc_qm57
2025arc_qm58
2025arc_qm59
2025arc_qm6
2025arc_qm60
2025arc_qm61
2025arc_qm62
2025arc_qm63
2025arc_qm64
2025arc_qm65
2025arc_qm66
2025arc_qm67
2025arc_qm68
2025arc_qm69
2025arc_qm7
2025arc_qm70
2025arc_qm71
2025arc_qm72
2025arc_qm73
2025arc_qm74
2025arc_qm75
2025arc_qm76
2025arc_qm77
2025arc_qm78
2025arc_qm79
2025arc_qm8
2025arc_qm80
2025arc_qm81
2025arc_qm82
2025arc_qm83
2025arc_qm84
2025arc_qm85
2025arc_qm86
2025arc_qm87
2025arc_qm88
2025arc_qm89
2025arc_qm9
2025arc_qm90
2025arc_qm91
2025arc_qm92
2025arc_qm93
2025arc_qm94
2025arc_qm95
2025arc_qm96
2025arc_qm97
2025arc_qm98
2025arc_qm99
2025arc_sf10m1
2025arc_sf11m1
2025arc_sf12m1
2025arc_sf13m1
2025arc_sf1m1
2025arc_sf2m1
2025arc_sf3m1
2025arc_sf4m1
2025arc_sf5m1
2025arc_sf6m1
2025arc_sf7m1
2025arc_sf8m1
2025arc_sf9m1
2025arli_f1m1
2025arli_f1m2
2025arli_qm1
2025arli_qm10
2025arli_qm11
2025arli_qm12
2025arli_qm13
2025arli_qm14
2025arli_qm15
2025arli_qm16
2025arli_qm17
2025arli_qm18
2025arli_qm19
2025arli_qm2
2025arli_qm20
2025arli_qm21
2025arli_qm22
2025arli_qm23
2025arli_qm24
2025arli_qm25
2025arli_qm26
2025arli_qm27
2025arli_qm28
2025arli_qm29
2025arli_qm3
2025arli_qm30
2025arli_qm31
2025arli_qm32
2025arli_qm33
2025arli_qm34
2025arli_qm35
2025arli_qm36
2025arli_qm37
2025arli_qm38
2025arli_qm39
2025arli_qm4
2025arli_qm40
2025arli_qm41
2025arli_qm42
2025arli_qm43
2025arli_qm44
2025arli_qm45
2025arli_qm46
2025arli_qm47
2025arli_qm48
2025arli_qm49
2025arli_qm5
2025arli_qm50
2025arli_qm51
2025arli_qm52
2025arli_qm53
2025arli_qm54
2025arli_qm55
2025arli_qm56
2025arli_qm57
2025arli_qm58
2025arli_qm59
2025arli_qm6
2025arli_qm60
2025arli_qm7
2025arli_qm8
2025arli_qm9
2025arli_sf10m1
2025arli_sf11m1
2025arli_sf12m1
2025arli_sf13m1
2025arli_sf1m1
2025arli_sf2m1
2025arli_sf3m1
2025arli_sf4m1
2025arli_sf5m1
2025arli_sf6m1
2025arli_sf7m1
2025arli_sf8m1
2025arli_sf9m1
2025ausc_f1m1
2025ausc_f1m2
2025ausc_qm1
2025ausc_qm10
2025ausc_qm11
2025ausc_qm12
2025ausc_qm13
2025ausc_qm14
2025ausc_qm15
2025ausc_qm16
2025ausc_qm17
2025ausc_qm18
2025ausc_qm19
2025ausc_qm2
2025ausc_qm20
2025ausc_qm21
2025ausc_qm22
2025ausc_qm23
2025ausc_qm24
2025ausc_qm25
2025ausc_qm26
2025ausc_qm27
2025ausc_qm28
2025ausc_qm29
2025ausc_qm3
2025ausc_qm30
2025ausc_qm31
2025ausc_qm32
2025ausc_qm33
2025ausc_qm34
2025ausc_qm35
2025ausc_qm36
2025ausc_qm37
2025ausc_qm38
2025ausc_qm39
2025ausc_qm4
2025ausc_qm40
2025ausc_qm41
2025ausc_qm42
2025ausc_qm43
2025ausc_qm44
2025ausc_qm45
2025ausc_qm46
2025ausc_qm47
2025ausc_qm48
2025ausc_qm49
2025ausc_qm5
2025ausc_qm50
2025ausc_qm51
2025ausc_qm52
2025ausc_qm53
2025ausc_qm54
2025ausc_qm55
2025ausc_qm56
2025ausc_qm57
2025ausc_qm58
2025ausc_qm59
2025ausc_qm6
2025ausc_qm60
2025ausc_qm61
2025ausc_qm62
2025ausc_qm63
2025ausc_qm64
2025ausc_qm65
2025ausc_qm66
2025ausc_qm67
2025ausc_qm68
2025ausc_qm69
2025ausc_qm7
2025ausc_qm70
2025ausc_qm71
2025ausc_qm72
2025ausc_qm73
2025ausc_qm74
2025ausc_qm75
2025ausc_qm76
2025ausc_qm8
2025ausc_qm9
2025ausc_sf10m1
2025ausc_sf11m1
2025ausc_sf12m1
2025ausc_sf13m1
2025ausc_sf1m1
2025ausc_sf2m1
2025ausc_sf3m1
2025ausc_sf4m1
2025ausc_sf5m1
2025ausc_sf6m1
2025ausc_sf7m1
2025ausc_sf8m1
2025ausc_sf9m1
2025azfg_f1m1
2025azfg_f1m2
2025azfg_f1m3
2025azfg_qm1
2025azfg_qm10
2025azfg_qm11
2025azfg_qm12
2025azfg_qm13
2025azfg_qm14
2025azfg_qm15
2025azfg_qm16
2025azfg_qm17
2025azfg_qm18
2025azfg_qm19
2025azfg_qm2
2025azfg_qm20
2025azfg_qm21
2025azfg_qm22
2025azfg_qm23
2025azfg_qm24
2025azfg_qm25
2025azfg_qm26
2025azfg_qm27
2025azfg_qm28
2025azfg_qm29
2025azfg_qm3
2025azfg_qm30
2025azfg_qm31
2025azfg_qm32
2025azfg_qm33
2025azfg_qm34
2025azfg_qm35
2025azfg_qm36
2025azfg_qm37
2025azfg_qm38
2025azfg_qm39
2025azfg_qm4
2025azfg_qm40
2025azfg_qm41
2025azfg_qm42
2025azfg_qm43
2025azfg_qm44
2025azfg_qm45
2025azfg_qm46
2025azfg_qm47
2025azfg_qm48
2025azfg_qm49
2025azfg_qm5
2025azfg_qm50
2025azfg_qm51
2025azfg_qm52
2025azfg_qm53
2025azfg_qm54
2025azfg_qm55
2025azfg_qm56
2025azfg_qm57
2025azfg_qm58
2025azfg_qm59
2025azfg_qm6
2025azfg_qm60
2025azfg_qm61
2025azfg_qm62
2025azfg_qm63
2025azfg_qm64
2025azfg_qm65
2025azfg_qm66
2025azfg_qm67
2025azfg_qm68
2025azfg_qm69
2025azfg_qm7
2025azfg_qm70
2025azfg_qm71
2025azfg_qm72
2025azfg_qm73
2025azfg_qm74
2025azfg_qm75
2025azfg_qm76
2025azfg_qm77
2025azfg_qm78
2025azfg_qm79
2025azfg_qm8
2025azfg_qm80
2025azfg_qm9
2025azfg_sf10m1
2025azfg_sf11m1
2025azfg_sf12m1
2025azfg_sf13m1
2025azfg_sf1m1
2025azfg_sf2m1
2025azfg_sf3m1
2025azfg_sf4m1
2025azfg_sf5m1
2025azfg_sf6m1
2025azfg_sf7m1
2025azfg_sf8m1
2025azfg_sf9m1
2025azgl_f1m1
2025azgl_f1m2
2025azgl_f1m3
2025azgl_qm1
2025azgl_qm10
2025azgl_qm11
2025azgl_qm12
2025azgl_qm13
2025azgl_qm14
2025azgl_qm15
2025azgl_qm16
2025azgl_qm17
2025azgl_qm18
2025azgl_qm19
2025azgl_qm2
2025azgl_qm20
2025azgl_qm21
2025azgl_qm22
2025azgl_qm23
2025azgl_qm24
2025azgl_qm25
2025azgl_qm26
2025azgl_qm27
2025azgl_qm28
2025azgl_qm29
2025azgl_qm3
2025azgl_qm30
2025azgl_qm31
2025azgl_qm32
2025azgl_qm33
2025azgl_qm34
2025azgl_qm35
2025azgl_qm36
2025azgl_qm37
2025azgl_qm38
2025azgl_qm39
2025azgl_qm4
2025azgl_qm40
2025azgl_qm41
2025azgl_qm42
2025azgl_qm43
2025azgl_qm44
2025azgl_qm45
2025azgl_qm46
2025azgl_qm47
2025azgl_qm48
2025azgl_qm49
2025azgl_qm5
2025azgl_qm50
2025azgl_qm51
2025azgl_qm52
2025azgl_qm53
2025azgl_qm54
2025azgl_qm55
2025azgl_qm56
2025azgl_qm57
2025azgl_qm58
2025azgl_qm59
2025azgl_qm6
2025azgl_qm60
2025azgl_qm61
2025azgl_qm62
2025azgl_qm63
2025azgl_qm64
2025azgl_qm65
2025azgl_qm66
2025azgl_qm67
2025azgl_qm68
2025azgl_qm69
2025azgl_qm7
2025azgl_qm70
2025azgl_qm71
2025azgl_qm72
2025azgl_qm73
2025azgl_qm74
2025azgl_qm75
2025azgl_qm76
2025azgl_qm77
2025azgl_qm8
2025azgl_qm9
2025azgl_sf10m1
2025azgl_sf11m1
2025azgl_sf12m1
2025azgl_sf13m1
2025azgl_sf1m1
2025azgl_sf2m1
2025azgl_sf3m1
2025azgl_sf4m1
2025azgl_sf5m1
2025azgl_sf6m1
2025azgl_sf7m1
2025azgl_sf8m1
2025azgl_sf9m1
2025azrl1_f1m1
2025azrl1_qm1
2025azrl1_qm10
2025azrl1_qm11
2025azrl1_qm12
2025azrl1_qm13
2025azrl1_qm14
2025azrl1_qm15
2025azrl1_qm16
2025azrl1_qm17
2025azrl1_qm18
2025azrl1_qm19
2025azrl1_qm2
2025azrl1_qm20
2025azrl1_qm21
2025azrl1_qm22
2025azrl1_qm23
2025azrl1_qm24
2025azrl1_qm3
2025azrl1_qm4
2025azrl1_qm5
2025azrl1_qm6
2025azrl1_qm7
2025azrl1_qm8
2025azrl1_qm9
2025azrl1_sf1m1
2025azrl1_sf2m1
2025azrl1_sf3m1
2025azrl1_sf4m1
2025azrl1_sf5m1
2025azrl2_f1m1
2025azrl2_qm1
2025azrl2_qm10
2025azrl2_qm11
2025azrl2_qm12
2025azrl2_qm13
2025azrl2_qm14
2025azrl2_qm15
2025azrl2_qm16
2025azrl2_qm17
2025azrl2_qm18
2025azrl2_qm2
2025azrl2_qm3
2025azrl2_qm4
2025azrl2_qm5
2025azrl2_qm6
2025azrl2_qm7
2025azrl2_qm8
2025azrl2_qm9
2025azrl2_sf1m1
2025azrl2_sf2m1
2025azrl2_sf3m1
2025azrl2_sf4m1
2025azrl2_sf5m1
2025azrl3_f1m1
2025azrl3_qm1
2025azrl3_qm10
2025azrl3_qm11
2025azrl3_qm12
2025azrl3_qm13
2025azrl3_qm14
2025azrl3_qm15
2025azrl3_qm16
2025azrl3_qm17
2025azrl3_qm18
2025azrl3_qm19
2025azrl3_qm2
2025azrl3_qm3
2025azrl3_qm4
2025azrl3_qm5
2025azrl3_qm6
2025azrl3_qm7
2025azrl3_qm8
2025azrl3_qm9
2025azrl3_sf1m1
2025azrl3_sf2m1
2025azrl3_sf3m1
2025azrl3_sf4m1
2025azrl3_sf5m1
2025azrl4_f1m1
2025azrl4_f1m2
2025azrl4_qm1
2025azrl4_qm10
2025azrl4_qm11
2025azrl4_qm12
2025azrl4_qm13
2025azrl4_qm14
2025azrl4_qm15
2025azrl4_qm16
2025azrl4_qm17
2025azrl4_qm18
2025azrl4_qm19
2025azrl4_qm2
2025azrl4_qm20
2025azrl4_qm21
2025azrl4_qm22
2025azrl4_qm23
2025azrl4_qm24
2025azrl4_qm25
2025azrl4_qm26
2025azrl4_qm27
2025azrl4_qm28
2025azrl4_qm29
2025azrl4_qm3
2025azrl4_qm30
2025azrl4_qm31
2025azrl4_qm32
2025azrl4_qm33
2025azrl4_qm4
2025azrl4_qm5
2025azrl4_qm6
2025azrl4_qm7
2025azrl4_qm8
2025azrl4_qm9
2025azrl4_sf1m1
2025azrl4_sf2m1
2025azrl4_sf3m1
2025azrl4_sf4m1
2025azrl4_sf5m1
2025azrl5_f1m1
2025azrl5_f1m2
2025azrl5_qm1
2025azrl5_qm10
2025azrl5_qm11
2025azrl5_qm12
2025azrl5_qm13
2025azrl5_qm14
2025azrl5_qm15
2025azrl5_qm16
2025azrl5_qm17
2025azrl5_qm18
2025azrl5_qm19
2025azrl5_qm2
2025azrl5_qm20
2025azrl5_qm21
2025azrl5_qm22
2025azrl5_qm23
2025azrl5_qm24
2025azrl5_qm25
2025azrl5_qm26
2025azrl5_qm27
2025azrl5_qm28
2025azrl5_qm29
2025azrl5_qm3
2025azrl5_qm30
2025azrl5_qm31
2025azrl5_qm32
2025azrl5_qm4
2025azrl5_qm5
2025azrl5_qm7
2025azrl5_qm8
2025azrl5_qm9
2025azrl5_sf1m1
2025azrl5_sf2m1
2025azrl5_sf3m1
2025azrl5_sf4m1
2025azrl5_sf5m1
2025bc_qm1
2025bc_qm10
2025bc_qm11
2025bc_qm12
2025bc_qm13
2025bc_qm14
2025bc_qm15
2025bc_qm16
2025bc_qm17
2025bc_qm18
2025bc_qm19
2025bc_qm2
2025bc_qm20
2025bc_qm21
2025bc_qm22
2025bc_qm23
2025bc_qm24
2025bc_qm25
2025bc_qm26
2025bc_qm27
2025bc_qm28
2025bc_qm29
2025bc_qm3
2025bc_qm30
2025bc_qm31
2025bc_qm32
2025bc_qm33
2025bc_qm34
2025bc_qm35
2025bc_qm36
2025bc_qm37
2025bc_qm38
2025bc_qm39
2025bc_qm4
2025bc_qm40
2025bc_qm41
2025bc_qm42
2025bc_qm43
2025bc_qm44
2025bc_qm45
2025bc_qm46
2025bc_qm47
2025bc_qm48
2025bc_qm49
2025bc_qm5
2025bc_qm50
2025bc_qm51
2025bc_qm52
2025bc_qm53
2025bc_qm54
2025bc_qm55
2025bc_qm56
2025bc_qm57
2025bc_qm58
2025bc_qm59
2025bc_qm6
2025bc_qm60
2025bc_qm61
2025bc_qm62
2025bc_qm63
2025bc_qm64
2025bc_qm65
2025bc_qm66
2025bc_qm67
2025bc_qm68
2025bc_qm69
2025bc_qm7
2025bc_qm70
2025bc_qm71
2025bc_qm72
2025bc_qm73
2025bc_qm74
2025bc_qm75
2025bc_qm76
2025bc_qm77
2025bc_qm78
2025bc_qm79
2025bc_qm8
2025bc_qm80
2025bc_qm81
2025bc_qm82
2025bc_qm83
2025bc_qm9
2025bcvi_f1m1
2025bcvi_f1m2
2025bcvi_f1m3
2025bcvi_qm1
2025bcvi_qm10
2025bcvi_qm11
2025bcvi_qm12
2025bcvi_qm13
2025bcvi_qm14
2025bcvi_qm15
2025bcvi_qm16
2025bcvi_qm17
2025bcvi_qm18
2025bcvi_qm19
2025bcvi_qm2
2025bcvi_qm20
2025bcvi_qm21
2025bcvi_qm22
2025bcvi_qm23
2025bcvi_qm24
2025bcvi_qm25
2025bcvi_qm26
2025bcvi_qm27
2025bcvi_qm28
2025bcvi_qm29
2025bcvi_qm3
2025bcvi_qm30
2025bcvi_qm31
2025bcvi_qm32
2025bcvi_qm33
2025bcvi_qm34
2025bcvi_qm35
2025bcvi_qm36
2025bcvi_qm37
2025bcvi_qm38
2025bcvi_qm39
2025bcvi_qm4
2025bcvi_qm40
2025bcvi_qm41
2025bcvi_qm42
2025bcvi_qm43
2025bcvi_qm44
2025bcvi_qm45
2025bcvi_qm46
2025bcvi_qm47
2025bcvi_qm48
2025bcvi_qm49
2025bcvi_qm5
2025bcvi_qm50
2025bcvi_qm51
2025bcvi_qm52
2025bcvi_qm53
2025bcvi_qm54
2025bcvi_qm55
2025bcvi_qm56
2025bcvi_qm57
2025bcvi_qm58
2025bcvi_qm59
2025bcvi_qm6
2025bcvi_qm60
2025bcvi_qm61
2025bcvi_qm62
2025bcvi_qm63
2025bcvi_qm64
2025bcvi_qm65
2025bcvi_qm66
2025bcvi_qm67
2025bcvi_qm68
2025bcvi_qm69
2025bcvi_qm7
2025bcvi_qm70
2025bcvi_qm71
2025bcvi_qm72
2025bcvi_qm73
2025bcvi_qm74
2025bcvi_qm75
2025bcvi_qm76
2025bcvi_qm77
2025bcvi_qm78
2025bcvi_qm79
2025bcvi_qm8
2025bcvi_qm80
2025bcvi_qm9
2025bcvi_sf10m1
2025bcvi_sf11m1
2025bcvi_sf12m1
2025bcvi_sf13m1
2025bcvi_sf1m1
2025bcvi_sf2m1
2025bcvi_sf3m1
2025bcvi_sf4m1
2025bcvi_sf5m1
2025bcvi_sf6m1
2025bcvi_sf7m1
2025bcvi_sf8m1
2025bcvi_sf9m1
2025brba_f1m1
2025brba_f1m2
2025brba_qm1
2025brba_qm11
2025brba_qm13
2025brba_qm15
2025brba_qm18
2025brba_qm2
2025brba_qm21
2025brba_qm22
2025brba_qm23
2025brba_qm24
2025brba_qm26
2025brba_qm27
2025brba_qm3
2025brba_qm31
2025brba_qm34
2025brba_qm35
2025brba_qm36
2025brba_qm38
2025brba_qm40
2025brba_qm45
2025brba_qm46
2025brba_qm47
2025brba_qm48
2025brba_qm51
2025brba_qm52
2025brba_qm53
2025brba_qm54
2025brba_qm55
2025brba_qm56
2025brba_qm58
2025brba_qm59
2025brba_qm61
2025brba_qm64
2025brba_qm65
2025brba_qm66
2025brba_qm68
2025brba_qm69
2025brba_qm70
2025brba_qm71
2025brba_qm73
2025brba_qm78
2025brba_qm8
2025brba_qm9
2025brba_sf10m1
2025brba_sf11m1
2025brba_sf12m1
2025brba_sf13m1
2025brba_sf1m1
2025brba_sf2m1
2025brba_sf3m1
2025brba_sf4m1
2025brba_sf5m1
2025brba_sf6m1
2025brba_sf7m1
2025brba_sf8m1
2025brba_sf9m1
2025brsp_f1m1
2025brsp_f1m2
2025brsp_qm1
2025brsp_qm10
2025brsp_qm11
2025brsp_qm12
2025brsp_qm13
2025brsp_qm14
2025brsp_qm15
2025brsp_qm16
2025brsp_qm17
2025brsp_qm18
2025brsp_qm19
2025brsp_qm2
2025brsp_qm20
2025brsp_qm21
2025brsp_qm22
2025brsp_qm23
2025brsp_qm24
2025brsp_qm25
2025brsp_qm26
2025brsp_qm27
2025brsp_qm28
2025brsp_qm29
2025brsp_qm3
2025brsp_qm30
2025brsp_qm31
2025brsp_qm32
2025brsp_qm33
2025brsp_qm34
2025brsp_qm35
2025brsp_qm36
2025brsp_qm37
2025brsp_qm38
2025brsp_qm39
2025brsp_qm4
2025brsp_qm40
2025brsp_qm41
2025brsp_qm42
2025brsp_qm43
2025brsp_qm44
2025brsp_qm45
2025brsp_qm46
2025brsp_qm47
2025brsp_qm48
2025brsp_qm49
2025brsp_qm5
2025brsp_qm50
2025brsp_qm51
2025brsp_qm52
2025brsp_qm53
2025brsp_qm54
2025brsp_qm55
2025brsp_qm56
2025brsp_qm57
2025brsp_qm58
2025brsp_qm59
2025brsp_qm6
2025brsp_qm60
2025brsp_qm61
2025brsp_qm62
2025brsp_qm63
2025brsp_qm64
2025brsp_qm65
2025brsp_qm66
2025brsp_qm7
2025brsp_qm8
2025brsp_qm9
2025brsp_sf10m1
2025brsp_sf11m1
2025brsp_sf12m1
2025brsp_sf13m1
2025brsp_sf1m1
2025brsp_sf2m1
2025brsp_sf3m1
2025brsp_sf4m1
2025brsp_sf5m1
2025brsp_sf6m1
2025brsp_sf7m1
2025brsp_sf8m1
2025brsp_sf9m1
2025caab_f1m1
2025caab_qm11
2025caab_qm13
2025caab_qm14
2025caab_qm15
2025caab_qm16
2025caab_qm17
2025caab_qm19
2025caab_qm2
2025caab_qm20
2025caab_qm21
2025caab_qm22
2025caab_qm24
2025caab_qm25
2025caab_qm27
2025caab_qm28
2025caab_qm29
2025caab_qm3
2025caab_qm30
2025caab_qm31
2025caab_qm32
2025caab_qm33
2025caab_qm4
2025caab_qm6
2025caab_qm7
2025caab_qm9
2025caab_sf1m1
2025caab_sf2m1
2025caab_sf3m1
2025caab_sf4m1
2025caab_sf5m1
2025caav_f1m1
2025caav_f1m2
2025caav_f1m3
2025caav_qm1
2025caav_qm10
2025caav_qm11
2025caav_qm12
2025caav_qm13
2025caav_qm14
2025caav_qm15
2025caav_qm16
2025caav_qm17
2025caav_qm18
2025caav_qm19
2025caav_qm2
2025caav_qm20
2025caav_qm21
2025caav_qm22
2025caav_qm23
2025caav_qm24
2025caav_qm25
2025caav_qm26
2025caav_qm27
2025caav_qm28
2025caav_qm29
2025caav_qm3
2025caav_qm30
2025caav_qm31
2025caav_qm32
2025caav_qm33
2025caav_qm34
2025caav_qm35
2025caav_qm36
2025caav_qm37
2025caav_qm38
2025caav_qm39
2025caav_qm4
2025caav_qm40
2025caav_qm41
2025caav_qm42
2025caav_qm43
2025caav_qm44
2025caav_qm45
2025caav_qm46
2025caav_qm47
2025caav_qm48
2025caav_qm49
2025caav_qm5
2025caav_qm50
2025caav_qm51
2025caav_qm52
2025caav_qm53
2025caav_qm54
2025caav_qm55
2025caav_qm56
2025caav_qm57
2025caav_qm58
2025caav_qm59
2025caav_qm6
2025caav_qm60
2025caav_qm61
2025caav_qm62
2025caav_qm63
2025caav_qm64
2025caav_qm65
2025caav_qm66
2025caav_qm67
2025caav_qm68
2025caav_qm69
2025caav_qm7
2025caav_qm70
2025caav_qm71
2025caav_qm72
2025caav_qm73
2025caav_qm74
2025caav_qm8
2025caav_qm9
2025caav_sf10m1
2025caav_sf11m1
2025caav_sf12m1
2025caav_sf13m1
2025caav_sf1m1
2025caav_sf2m1
2025caav_sf3m1
2025caav_sf4m1
2025caav_sf5m1
2025caav_sf6m1
2025caav_sf7m1
2025caav_sf8m1
2025caav_sf9m1
2025cabe_f1m1
2025cabe_f1m2
2025cabe_qm1
2025cabe_qm10
2025cabe_qm11
2025cabe_qm12
2025cabe_qm14
2025cabe_qm15
2025cabe_qm16
2025cabe_qm17
2025cabe_qm18
2025cabe_qm19
2025cabe_qm2
2025cabe_qm20
2025cabe_qm21
2025cabe_qm22
2025cabe_qm23
2025cabe_qm25
2025cabe_qm26
2025cabe_qm27
2025cabe_qm29
2025cabe_qm30
2025cabe_qm31
2025cabe_qm32
2025cabe_qm33
2025cabe_qm34
2025cabe_qm35
2025cabe_qm37
2025cabe_qm39
2025cabe_qm4
2025cabe_qm40
2025cabe_qm41
2025cabe_qm42
2025cabe_qm44
2025cabe_qm45
2025cabe_qm46
2025cabe_qm47
2025cabe_qm48
2025cabe_qm5
2025cabe_qm50
2025cabe_qm51
2025cabe_qm52
2025cabe_qm53
2025cabe_qm54
2025cabe_qm56
2025cabe_qm57
2025cabe_qm58
2025cabe_qm59
2025cabe_qm6
2025cabe_qm60
2025cabe_qm61
2025cabe_qm62
2025cabe_qm64
2025cabe_qm67
2025cabe_qm68
2025cabe_qm69
2025cabe_qm7
2025cabe_qm70
2025cabe_qm71
2025cabe_qm72
2025cabe_qm74
2025cabe_qm76
2025cabe_qm78
2025cabe_qm79
2025cabe_qm8
2025cabe_qm80
2025cabe_qm82
2025cabe_qm83
2025cabe_qm9
2025cabe_sf10m1
2025cabe_sf11m1
2025cabe_sf12m1
2025cabe_sf13m1
2025cabe_sf1m1
2025cabe_sf2m1
2025cabe_sf3m1
2025cabe_sf4m1
2025cabe_sf5m1
2025cabe_sf6m1
2025cabe_sf7m1
2025cabe_sf8m1
2025cabe_sf9m1
2025cada_f1m1
2025cada_f1m2
2025cada_qm1
2025cada_qm10
2025cada_qm11
2025cada_qm12
2025cada_qm13
2025cada_qm14
2025cada_qm15
2025cada_qm16
2025cada_qm17
2025cada_qm18
2025cada_qm19
2025cada_qm2
2025cada_qm20
2025cada_qm21
2025cada_qm22
2025cada_qm23
2025cada_qm24
2025cada_qm25
2025cada_qm26
2025cada_qm27
2025cada_qm28
2025cada_qm29
2025cada_qm3
2025cada_qm30
2025cada_qm31
2025cada_qm32
2025cada_qm33
2025cada_qm34
2025cada_qm35
2025cada_qm36
2025cada_qm37
2025cada_qm38
2025cada_qm39
2025cada_qm4
2025cada_qm40
2025cada_qm41
2025cada_qm42
2025cada_qm43
2025cada_qm44
2025cada_qm45
2025cada_qm46
2025cada_qm47
2025cada_qm48
2025cada_qm49
2025cada_qm5
2025cada_qm50
2025cada_qm51
2025cada_qm52
2025cada_qm53
2025cada_qm54
2025cada_qm55
2025cada_qm56
2025cada_qm57
2025cada_qm58
2025cada_qm59
2025cada_qm6
2025cada_qm60
2025cada_qm61
2025cada_qm62
2025cada_qm63
2025cada_qm64
2025cada_qm65
2025cada_qm66
2025cada_qm67
2025cada_qm68
2025cada_qm7
2025cada_qm8
2025cada_qm9
2025cada_sf10m1
2025cada_sf11m1
2025cada_sf12m1
2025cada_sf13m1
2025cada_sf1m1
2025cada_sf2m1
2025cada_sf3m1
2025cada_sf4m1
2025cada_sf5m1
2025cada_sf6m1
2025cada_sf7m1
2025cada_sf8m1
2025cada_sf9m1
2025cafr_f1m1
2025cafr_f1m2
2025cafr_qm1
2025cafr_qm10
2025cafr_qm11
2025cafr_qm12
2025cafr_qm13
2025cafr_qm14
2025cafr_qm15
2025cafr_qm16
2025cafr_qm17
2025cafr_qm18
2025cafr_qm19
2025cafr_qm2
2025cafr_qm20
2025cafr_qm21
2025cafr_qm22
2025cafr_qm23
2025cafr_qm24
2025cafr_qm25
2025cafr_qm26
2025cafr_qm27
2025cafr_qm28
2025cafr_qm29
2025cafr_qm3
2025cafr_qm30
2025cafr_qm31
2025cafr_qm32
2025cafr_qm33
2025cafr_qm34
2025cafr_qm35
2025cafr_qm36
2025cafr_qm37
2025cafr_qm38
2025cafr_qm39
2025cafr_qm4
2025cafr_qm40
2025cafr_qm41
2025cafr_qm42
2025cafr_qm43
2025cafr_qm44
2025cafr_qm45
2025cafr_qm46
2025cafr_qm47
2025cafr_qm48
2025cafr_qm49
2025cafr_qm5
2025cafr_qm50
2025cafr_qm51
2025cafr_qm52
2025cafr_qm53
2025cafr_qm54
2025cafr_qm55
2025cafr_qm56
2025cafr_qm57
2025cafr_qm58
2025cafr_qm59
2025cafr_qm6
2025cafr_qm60
2025cafr_qm61
2025cafr_qm62
2025cafr_qm63
2025cafr_qm64
2025cafr_qm65
2025cafr_qm66
2025cafr_qm67
2025cafr_qm68
2025cafr_qm69
2025cafr_qm7
2025cafr_qm70
2025cafr_qm71
2025cafr_qm72
2025cafr_qm73
2025cafr_qm74
2025cafr_qm75
2025cafr_qm76
2025cafr_qm77
2025cafr_qm8
2025cafr_qm9
2025cafr_sf10m1

# logistic reggresion

In [78]:
X = df.drop(['win', 'event_key', 'key', 'videos'], axis = 1)
y = df['win']

In [79]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 42)

In [69]:
df.columns[df.isnull().any()]

Index(['winning_alliance'], dtype='object')

In [82]:
clf = LogisticRegression(random_state=0).fit(X_train, y_train)