In [1]:
import requests
import pandas as pd

In [ ]:
AUTH_KEY = "Tnuge6o2FKoppKZ7DZaeFgbnyXRFivvrI6FPwao5XhhcPzkCOT2K525UTbqKr13o" 

headers = {
    "X-TBA-Auth-Key": AUTH_KEY.strip()
}

team_data = []
page_num = 0

while True:
    url = f"https://www.thebluealliance.com/api/v3/teams/{page_num}/simple"
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        break
        
    teams = response.json()
    if not teams:
        break

    for team in teams:
        team_data.append({
            "TeamNum": team.get("team_number"),
            "TeamName": team.get("nickname"),
            "Country": team.get("country")
        })
        
    page_num += 1

df = pd.DataFrame(team_data)

file_path = r"C:\Projects\Statbotics\RomiRotem\data\datasets\X.csv"
df.to_csv(file_path, index=False)

In [11]:
df

      TeamNum                   TeamName
0           1            The Juggernauts
1           4             Team 4 ELEMENT
2           5                  Robocards
3           6               The CogSquad
4           7                    Team007
...       ...                        ...
9158    11503                     TALONS
9159    11505  Kensington Woods Robotics
9160    11511                  GearHeads
9161    11522                   Union HS
9162    11527           FCCA Chrome Crew

[9163 rows x 2 columns]

In [12]:
df.loc[df['TeamNum'] == 1574]

      TeamNum TeamName
1288     1574   MisCar