In [1]:
import requests
import pandas as pd

In [19]:
AUTH_KEY = "Tnuge6o2FKoppKZ7DZaeFgbnyXRFivvrI6FPwao5XhhcPzkCOT2K525UTbqKr13o" 

headers = {
    "X-TBA-Auth-Key": AUTH_KEY.strip()
}

team_data = []
page_num = 0

while True:
    url = f"https://www.thebluealliance.com/api/v3/teams/{page_num}/simple"
    response = requests.get(url, headers=headers)
    if response.status_code != 200:
        break
        
    teams = response.json()
    if not teams:
        break

    for team in teams:
        team_data.append({
            "TeamNum": team.get("team_number"),
            "TeamName": team.get("nickname"),
            "TeamCountry": team.get("country"),
            "TeamCity": team.get("city")
        })
        
    page_num += 1

df = pd.DataFrame(team_data)

In [20]:
df

      TeamNum                   TeamName TeamCountry      TeamCity
0           1            The Juggernauts         USA       Pontiac
1           4             Team 4 ELEMENT         USA      Van Nuys
2           5                  Robocards         USA    Melvindale
3           6               The CogSquad         USA      Plymouth
4           7                    Team007         USA     Baltimore
...       ...                        ...         ...           ...
9158    11503                     TALONS         USA     Clarkston
9159    11505  Kensington Woods Robotics         USA      Lakeland
9160    11511                  GearHeads         USA    Litchfield
9161    11522                   Union HS         USA  Grand Rapids
9162    11527           FCCA Chrome Crew         USA         Flint

[9163 rows x 4 columns]

In [21]:
df.loc[df['TeamNum'] == 1574]

      TeamNum TeamName TeamCountry TeamCity
1288     1574   MisCar      Israel   Misgav

In [23]:
file_path = r"C:\Projects\Statbotics\RomiRotem\data\datasets\teams_backup.csv"
df.to_csv(file_path, index=False)

In [24]:
file_path = r"C:\Projects\Statbotics\RomiRotem\full_project\frontend\public\teams.csv"
df.to_csv(file_path, index=False)