In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
path = r'C:\Users\Magsihim_AI\Desktop\Project_Statbotics\data\datasets\final_table.csv'

df = pd.read_csv(path)

In [3]:
df

,comp_level,event_key,match_number,set_number,score,algaePoints,autoBonusAchieved,autoCoralCount,autoCoralPoints,autoLine,...,teleopReef_trough,wallAlgaeCount,team_number,scorePenaltyFree,possition,red,blue,winning_red,winning_blue,win
0,2,0,1,1,124,32.0,False,4.0,28.0,True,...,0.0,0.0,2783,124.0,1,True,False,False,True,False
1,2,0,2,1,144,28.0,False,3.0,21.0,True,...,0.0,0.0,2783,144.0,1,True,False,False,True,False
2,0,0,1,1,129,28.0,False,3.0,21.0,True,...,5.0,2.0,5045,129.0,1,True,False,True,False,True
3,0,0,10,1,118,8.0,True,3.0,21.0,True,...,1.0,0.0,538,112.0,1,True,False,True,False,True
4,0,0,11,1,67,14.0,False,1.0,3.0,True,...,1.0,1.0,6107,61.0,1,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114367,1,228,1,5,64,0.0,False,1.0,3.0,True,...,6.0,0.0,9995,64.0,3,False,True,True,False,False
114368,1,228,1,6,72,0.0,False,1.0,4.0,True,...,1.0,0.0,9991,72.0,3,False,True,False,True,True
114369,1,228,1,7,77,32.0,False,1.0,3.0,True,...,0.0,0.0,9994,65.0,3,False,True,True,False,False
114370,1,228,1,8,79,0.0,False,2.0,10.0,True,...,14.0,0.0,9993,73.0,3,False,True,True,False,False
114371,1,228,1,9,61,0.0,False,0.0,0.0,True,...,1.0,0.0,9991,57.0,3,False,True,True,False,False

In [4]:
drops = ['comp_level', 'event_key', 'match_number', 'set_number', 'algaePoints', 'autoBonusAchieved', 'autoCoralCount', 'autoCoralPoints', 'autoMobilityPoints', 'autoPoints', 'bargeBonusAchieved', 'coopertitionCriteriaMet', 'coralBonusAchieved', 'foulPoints', 'g410Penalty', 'g418Penalty', 'g428Penalty', 'rp', 'teleopCoralCount', 'teleopCoralPoints', 'teleopPoints', 'scorePenaltyFree', 'red', 'blue', 'winning_red', 'winning_blue', 'endGameBargePoints']

In [5]:
df.drop(drops, axis = 1, inplace = True)

In [6]:
df.drop(['teleopReef_tba_botRowCount', 'teleopReef_tba_midRowCount', 'teleopReef_tba_topRowCount', 'autoReef_tba_botRowCount', 'autoReef_tba_midRowCount', 'autoReef_tba_topRowCount'], axis = 1, inplace = True)

In [7]:
df

,score,autoLine,autoReef_botRow_nodeA,autoReef_botRow_nodeB,autoReef_botRow_nodeC,autoReef_botRow_nodeD,autoReef_botRow_nodeE,autoReef_botRow_nodeF,autoReef_botRow_nodeG,autoReef_botRow_nodeH,...,teleopReef_topRow_nodeH,teleopReef_topRow_nodeI,teleopReef_topRow_nodeJ,teleopReef_topRow_nodeK,teleopReef_topRow_nodeL,teleopReef_trough,wallAlgaeCount,team_number,possition,win
0,124,True,False,False,False,False,False,False,False,False,...,True,True,False,False,True,0.0,0.0,2783,1,False
1,144,True,False,False,False,False,False,False,False,False,...,True,True,True,True,False,0.0,0.0,2783,1,False
2,129,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,5.0,2.0,5045,1,True
3,118,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,1.0,0.0,538,1,True
4,67,True,False,False,False,False,False,False,False,False,...,False,False,True,True,True,1.0,1.0,6107,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114367,64,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,6.0,0.0,9995,3,False
114368,72,True,False,False,False,False,False,True,False,False,...,False,False,False,False,False,1.0,0.0,9991,3,True
114369,77,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,0.0,0.0,9994,3,False
114370,79,True,False,False,False,False,False,False,False,False,...,False,False,True,True,True,14.0,0.0,9993,3,False
114371,61,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,1.0,0.0,9991,3,False

In [8]:
df.to_csv(r"C:\Users\Magsihim_AI\Desktop\Project_Statbotics\actions_data\datasets\actions_df.csv", index=False)